# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
f0cpp <- function(ii, dd, nrows) {
    .Call('TenxRowSumTests_f0cpp', PACKAGE = 'TenxRowSumTests', ii, dd, nrows)
}

#' @export
f3cpp <- function(i0, i1, nrows, fnamev) {
    .Call('TenxRowSumTests_f3cpp', PACKAGE = 'TenxRowSumTests', i0, i1, nrows, fnamev)
}

